-- Script para agregar el departamento "Direccion general"
-- Actualizar ENUM en solicitudes_pago
ALTER TABLE solicitudes_pago 
MODIFY COLUMN departamento ENUM(
  'sistemas',
  'recursos humanos',
  'comercial',
  'finanzas',
  'operaciones',
  'marketing',
  'administracion',
  'ventas',
  'logistica',
  'calidad',
  'compras',
  'legal',
  'contabilidad',
  'tesoreria',
  'auditoria',
  'planeacion',
  'desarrollo',
  'soporte',
  'mantenimiento',
  'seguridad',
  'comunicaciones',
  'relaciones publicas',
  'capacitacion',
  'nominas',
  'cobranza',
  'credito',
  'facturacion',
  'almacen',
  'produccion',
  'automatizaciones',
  'atraccion de talento',
  'direccion general'
) NOT NULL;

-- Actualizar ENUM en solicitudes_viaticos
ALTER TABLE solicitudes_viaticos 
MODIFY COLUMN departamento ENUM(
  'sistemas',
  'recursos humanos',
  'comercial',
  'finanzas',
  'operaciones',
  'marketing',
  'administracion',
  'ventas',
  'logistica',
  'calidad',
  'compras',
  'legal',
  'contabilidad',
  'tesoreria',
  'auditoria',
  'planeacion',
  'desarrollo',
  'soporte',
  'mantenimiento',
  'seguridad',
  'comunicaciones',
  'relaciones publicas',
  'capacitacion',
  'nominas',
  'cobranza',
  'credito',
  'facturacion',
  'almacen',
  'produccion',
  'automatizaciones',
  'atraccion de talento',
  'direccion general'
) NOT NULL;

-- Actualizar ENUM en recurrentes si existe
ALTER TABLE recurrentes 
MODIFY COLUMN departamento ENUM(
  'sistemas',
  'recursos humanos',
  'comercial',
  'finanzas',
  'operaciones',
  'marketing',
  'administracion',
  'ventas',
  'logistica',
  'calidad',
  'compras',
  'legal',
  'contabilidad',
  'tesoreria',
  'auditoria',
  'planeacion',
  'desarrollo',
  'soporte',
  'mantenimiento',
  'seguridad',
  'comunicaciones',
  'relaciones publicas',
  'capacitacion',
  'nominas',
  'cobranza',
  'credito',
  'facturacion',
  'almacen',
  'produccion',
  'automatizaciones',
  'atraccion de talento',
  'direccion general'
) NOT NULL;
